- name: Build Banking App
        uses: docker/build-push-action@v5
        with:
          context: ./banking-app  # Change this from '.' to './banking-app'
          file: ./banking-app/Dockerfile
          push: false
          tags: banking-app:test
